//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.14 at 12:20:59 AM MMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.testing.com/my22/soap/entity", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.testing.my22.soap.entity;
